# Generated by Django 2.2.7 on 2019-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('user', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=255)),
            ],
        ),
    ]
